name: Build and Push Backend to ecr
ubuntu-24.04-arm
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm # Specify the arm64 runner
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.APPS_ECR_REPO }}
        IMAGE_TAG: api_latest
      run: |
        docker build --file ./backend/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Clean-up of ECR untagged images
      id: ecr-cleanup
      run: |
        bash ./build/cleanup_ecr.sh
